[project]
name = "spanish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "python-dotenv>=1.0.0",
    "tqdm>=4.66.0",
    "google-cloud-texttospeech>=2.14.0",
]
